### ISSUE TITLE
Code Smell on Video Constructor

### ISSUE THREAD

**Issue by liddyjacob** [liddyjacob/StreamVideo#1]
The primitive obsession on the *Video* constructor makes the code harder to understand.

EDIT:
In particular, there were too many parameters on the video constructor, so a parameter object should be created.

**Comment by liddyjacob** [comment]
This is no longer an issue, it has been taken care of.

**Comment by bmb134** [comment]
If the issue "has been taken care of," should we close it?

**Comment by liddyjacob** [comment]
Probably should, but don't delete the branches.

**Comment by bmb134** [comment]
I don't see that this TODO was handled in any branch, are you sure that you pushed your changes into GitHub?

**Comment by liddyjacob** [comment]
I don't think I wrote a TODO. I forgot to.
