### ISSUE TITLE
Stream output is ugly

### ISSUE THREAD

**Issue by liddyjacob** [liddyjacob/StreamVideo#11]
When you run ./StreamingActivity,it outputs...
```
Streams:
	The Lord of the Rings: The Fellowship of the Ring	9
	The Lord of the Rings: The Two Towers	3
	The Lord of the Rings: The Return of the King	6
```
This is ugly, and we can make this look better.

**Comment by bmb134** [comment]
the number of times watched is tripled for some strange reason

**Comment by liddyjacob** [comment]
I thought that was a bug at first, but then I looked at account.cpp. Those numbers are the 'stream count' of each stream, and they are actually correct 

For movies, the stream count is (hours) * (number of occurrences) watched  since the user watched The Fellowship of the Rings three times, the 'stream count' is 3 * 3 = 9. 

The issue here is, as you noticed, the output is very confusing. The output should probably tell you that those numbers are the stream count of each move. Here is what I think the output should look like:
```
Streams:
|                                 Title                                        |  Stream Count 
|The Lord of the Rings: The Fellowship of the Ring |       9
|The Lord of the Rings: The Two Towers                 |       3
|The Lord of the Rings: The Return of the King	 |       6
```

**Comment by liddyjacob** [comment]
That comment kinda turned out ugly, but I think we should make some sort of basic table for the streams output.

**Comment by bmb134** [comment]
why does the number of streams change depending on the type?
https://github.com/liddyjacob/StreamVideo/blob/a63c5378484308d6c4c37a73bfa5c567b59a525d/Account.cpp#L64-L82

**Comment by oreoeo** [comment]
I believe it is so it can count the number of originals in the total number of streams.

**Comment by liddyjacob** [comment]
I don't know. But I don't think we are supposed to change it. I would guess Dr. Collard just put it in there as a useless function for us to refactor.

Here is another output idea:
```
Streams:
 Format:   "Title"(Stream Count)
    "The Lord of the Rings: The Fellowship of the Ring"(SC:9)
    "The Lord of the Rings: The Two Towers"(SC:3)
    "The Lord of the Rings: The Return of the King"(SC:6)

```

**Comment by liddyjacob** [comment]
Also, not to get  too off topic, but how do you add code to your comment like that bmb134? Seems like a useful tool.

**Comment by bmb134** [comment]
But should we have it that way we already have total hours and times watched

**Comment by bmb134** [comment]
#15 This is the link to my pull request.  This is how I would fix it.  I am still not sure about how we should handle the strange repeated number of hours in data().

**Comment by liddyjacob** [comment]
For the first part(customer.report()), much better. However, for the second part(customer.data), the output should be in CSV format.

CSV format is for data management, so customer.data() should actually output this mess:

```
Fred,MOVIE,The Lord of the Rings: The Fellowship of the Ring,3,24,3
Fred,MOVIE,The Lord of the Rings: The Two Towers,3,19,1
Fred,MOVIE,The Lord of the Rings: The Return of the King,3,20,2
Fred,ORIGINAL,The Original Movie,2,7,1
Fred,TVSHOW,Friends,0,26,1
```

**Comment by bmb134** [comment]
They why are ewe printing it to the customer
 I really don't see what we lose by making it clear
We already have the CSV in a file why would we print it that makes no sense
