### ISSUE TITLE
I cant do anything 

### ISSUE THREAD

**Issue by bmb134** [liddyjacob/StreamVideo#12]
I have texted and emailed many times since 24+ hours ago 
PLEASE MAKE ME A CONTRIBUTOR!

**Comment by liddyjacob** [comment]
You should be able to with the gear icon on the right. What issue do you want? I will assign you.

**Comment by liddyjacob** [comment]
https://github.com/liddyjacob/StreamVideo/invitations

**Comment by liddyjacob** [comment]
Does that work?

**Comment by bmb134** [comment]
yes it is fine now

**Comment by liddyjacob** [comment]
Sorry about the delay
